name: Build and Deploy

on:
  push:
    branches: [develop]
    
 #Run workflow manually
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@develop
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build
      - name: Archive production artifact
        uses: action/upload-artifact@develop
        with:
          name: dist
          path: dist
  deploy:
    name: Deply
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@develop
      - name: Download artifact
        uses: actions/download-artifact@develop
        with:
          name: dist
          path: dist
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --onlly hosting
        env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  
  
